### ISSUE TITLE
openWEC_custom.py - bug in call to pn.calcM ?

### ISSUE THREAD

**Issue by namawakame** [tverbrug/openWEC#2]
Hello.

Thanks for sharing openWEC.  

I might have found a small bug in the call to pn.calcM in openWEC_custom.py  I'm new to WEC technology and associated modelling, and also python, so could be wrong, so haven't pushed up a fix, but I'm sure it'll be an easy fix if it is a bug.

The issue concerns line 2079 in openWEC_custom.py.  Here pn.calcM is called with the value of rho that was set to 1025 (sea water density) on line 2037.

It was my understanding that the M calculated in pn.calcM (line 159 of processNemoh.py) was the mass of the WEC buoy, so I had expected the density of the buoy to be passed in to the function, rather than the density of sea water (i.e. I expected the value of rho that is set when defining the geometry of the shape in the first tab of openWEC).

[ calcM is also called with a value of rho=1025 on line 1534, but I've not looked as hard at that part of the code.  Also similar calls seem to be made in openWEC_WS.py etc. ]

Again, apologies if this is my misunderstanding - I'm new to all this - and thanks again for sharing your code.

**Comment by tverbrug** [comment]
Hello!

Thank you for your question! The reason the density equals the density of water is because the Mass of the WEC is calculated based on the volume of water it displaces. Archimedes law dictates that the mass of a floating body is equal to the mass of the water volume it displaces. In the results of Nemoh, we get the volume of the displaced water, which multiplied with the density of water gives the Mass of the WEC body.

However you are correct that there is a small bug where rho=1025 is hard coded instead of taking the value given in the GUI.

I hope my answer is clear, and will fix the density bug as soon as possible!

Cheers!

**Comment by namawakame** [comment]
Ah, thank you!  I had not realised that Nemoh was calculating the volume of water rather than the volume of the shape.  I'll continue to learn...

Cheers!

**Comment by namawakame** [comment]
Sorry to bother you again, but I've spotted some other behaviour related to the entered density value that I don't quite understand.

I have a case which I run and then store a copy of the tec files:
   DiffractionForce.tec, ExcitationForce.tec, FKForce.tec, RadiationCoefficients.tec
and dat files
   Hydrostatics.dat, KH.dat

I then multiply the density in the "Mesh Tool" tab by 0.5 and run again and store the new copy of the above files.

Comparing the files I find that all of the files are identical, except that the entries in the KH.dat file are 0.5 times smaller in the second run.

I would not expect the stiffness to be affected by a change in the density of the body (it should just be rho_water x g x area ?) - I would have expected all of the files to be identical since for the Nemoh calculation only the location of the body is important?

(The net effect of this is that greater absorbed powers are produced in the simulation in the second case because the stiffness has become smaller by reducing the WEC density.)

Is this a bug?  If so it would seem to be due to the value from rhoBox (openWEC_custom.py) being passed in to ne.createMeshOpt and being written to the Mesh.cal file.

Again, apologies if I have misunderstood something!

[ Actually it is not clear to me where the WEC density input is actually used, since its only purpose seems to be to define the float mass - but in your previous reply you noted that this is calculated from the Nemoh displacement via Archimides priciple, so perhaps the WEC density is not actually required as an input (since it is implicit from the Posotion of COG input?) ]

**Comment by tverbrug** [comment]
Hi!

There were indeed some instances in openWEC_custom.py where the rho values were hard coded. I have changed all of these to accept the value of rhobox if it is filled in. Now the correct density should be used and your problems should be solved.

Cheers!

**Comment by namawakame** [comment]
Thanks for this!

Just to be clear about the rho value in the "Mesh Tool" tab - is this the density of the fluid or the WEC?  From your comment above I guess it is the fluid, but then how to I define the mass of the WEC for use in the power simulation - since it is needed to define total mass = added mass + WEC mass?  

(I had originally thought that this was the purpose of the density input in the mesh tool, which also knows the volume of the WEC, so could calculate its mass.)

Thanks again, and sorry for all of the questions!

**Comment by tverbrug** [comment]
Hello!

The density is the water density. The mesh you create will be automatically cut off above the water line so only the under water part remains. The Mass of the underwater volume is the Same as the mass of the device itself. So from the volume from the hydrostatics.dat you can calculate the device mass as rho_water*displacement. This is Archimedes law.

I hope this helps!

Kind regards

Op 30 mei 2016 23:16 schreef Namawakame notifications@github.com:

Thanks for this!

Just to be clear about the rho value in the "Mesh Tool" tab - is this the density of the fluid or the WEC? From your comment above I guess it is the fluid, but then how to I define the mass of the WEC for use in the power simulation - since it is needed to define total mass = added mass + WEC mass?

(I had originally thought that this was the purpose of the density input in the mesh tool, which also knows the volume of the WEC, so could calculate its mass.)

Thanks again, and sorry for all of the questions!

**Comment by namawakame** [comment]
Thanks for the clarification and fixes!
